site_name: HomeSetup
site_url: https://HS-Teams.github.io/homesetup

docs_dir: docs

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.top
    - content.code.copy

repo_url: https://github.com/HS-Teams/homesetup
repo_name: HS-Teams/homesetup

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - tables
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.mark

nav:
  - Home: 'index.md'
  - Handbook:
    - Overview: 'handbook/handbook.md'
    - Pages:
      - Applications Overview: 'handbook/pages/applications.md'
      - Functions Overview: 'handbook/pages/functions.md'
      - Applications: # Start of the nested folder content
        - hhs-app: 'handbook/pages/applications/bash/hhs-app/hhs-app.md'
        - check-ip: 'handbook/pages/applications/bash/check-ip.md'
        - fetch: 'handbook/pages/applications/bash/fetch.md'
      - Functions: # Start of the nested folder content
        - dev-tools: 'handbook/pages/functions/dev-tools/docker-tools.md'
        - std-tools: 'handbook/pages/functions/std-tools/aliases-related.md'
  - Misc:
    - CHANGELOG: 'CHANGELOG.md'
    - Code of Conduct: 'CODE_OF_CONDUCT.md'
    - Color LS Setup: 'COLOR_LS_SETUP.md'
    - Contributing: 'CONTRIBUTING.md'
    - Firebase Setup: 'FIREBASE_SETUP.md'
    - Showcase: 'SHOWCASE.md'
    - Usage: 'USAGE.md'
